### ISSUE TITLE
MCC version > Add option to not use parallel execution

### ISSUE THREAD

**Issue by luukfiets** [jzdarsa/google_ads_script_utm_tracking#4]
A colleague of mine linked to your script. I've written a similar script myself, but decided not to use the execute in parallel function as that limits you to process only 50 accounts, while in fact our script (w/o processing accounts in parallel) processes 140 scripts in 5 minutes.

While in theory it is safer to use the execute in parallel function, you can help people with MCC's larger than 50 accounts by processings the accounts sequentially. Depending on the size of each account, I'd estimate that you can run the script on about 700-900 accounts when processing them sequentially.

**Comment by jzdarsa** [comment]
Thanks for the suggestion and I agree that for some accounts your suggestion can be a better approach but for some other accounts without any labeling logic this could be pretty problematic approach. I decided to share just a very simple script without any complexity as I expect all agencies have their logic how to process more accounts for many other tasks they do with Google Ads Scripts.

If I change the logic to not process in parallel this can be problematic with massive Google Ads accounts as each Google Ads account can have up to 50k campaigns and it would not be able to process even 50 accounts. The execution time depends on the number of campaigns. So I agree with you that for simpler accounts your solution can be a better solution but for ecomm players with robust accounts this would be worse. 

If someone wants to process more than 50 accounts I assume they run it in parallel but they don't process just one batch but they have a logic in place to run multiple batches. For example using this solution: https://searchengineland.com/thinking-reusable-code-mcc-scripts-192836
